name: Test Package

on: push

env:
  SRH_TOKEN: example_token

jobs:
  test-core:
    name: Testing Core Package
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run library tests
        run: |
          pnpm install
          pnpm nx test core
